# On part d'une image Nginx légère
FROM nginx:alpine

# On copie nos fichiers HTML/CSS/JS dans le dossier par défaut de Nginx
COPY src /usr/share/nginx/html

# On dit que ce conteneur écoute sur le port 80 (standard web)
EXPOSE 80